Fix integration tests
Signed-off-by: Sorin Dumitru <sorin@returnze.ro>

diff --git a/test/integration/suites/fetch-wit-svids/03-mint-svid b/test/integration/suites/fetch-wit-svids/03-mint-svid
--- a/test/integration/suites/fetch-wit-svids/03-mint-svid
+++ b/test/integration/suites/fetch-wit-svids/03-mint-svid
@@ -1,13 +1,31 @@
 #!/bin/bash
 
 for format in pretty json; do
-  for keyType in ec-p256 ec-p384 rsa-2048 rsa-4096; do
+  for keySigningAlgCombo in ec-p256:ES256 ec-p384:ES384 rsa-2048:RS256 rsa-4096:RS512; do
+    keyType=$(echo $keySigningAlgCombo | cut -f 1 -d ':')
+    signingAlgorithm=$(echo $keySigningAlgCombo | cut -f 2 -d ':')
+
     docker compose exec -T -e SPIRE_SERVER_FFLAGS="wit-svid" spire-server /opt/spire/bin/spire-server \
       wit mint -spiffeID "spiffe://domain.test/workload" \
       -keyType "${keyType}" \
-      -output ${format} || fail-now "could not mint WIT-SVID using key type: ${keyType}"
+      -signingAlgorithm "${signingAlgorithm}" \
+      -output ${format} || fail-now "could not mint WIT-SVID using key type '${keyType}' and signing algorithm '${signingAlgorithm}'"
   done
 done
+
+# Check and invalid signing algorithm
+docker compose exec -T -e SPIRE_SERVER_FFLAGS="wit-svid" spire-server /opt/spire/bin/spire-server \
+  wit mint -spiffeID "spiffe://domain.test/workload" \
+  -keyType "ec-p256" \
+  -signingAlgorithm "ES123" \
+  -output ${format} && fail-now "could mint WIT-SVID with invalid signing algorithm"
+
+# Check and invalid signing algorithm for the specified key type
+docker compose exec -T -e SPIRE_SERVER_FFLAGS="wit-svid" spire-server /opt/spire/bin/spire-server \
+  wit mint -spiffeID "spiffe://domain.test/workload" \
+  -keyType "ec-p256" \
+  -signingAlgorithm "RS256" \
+  -output ${format} && fail-now "could mint WIT-SVID with invalid signing algorithm for key type"
 
 # Check that we can specify a custom TTL
 docker compose exec -T -e SPIRE_SERVER_FFLAGS="wit-svid" spire-server /opt/spire/bin/spire-server \
