Check if healthcheck passes using ifs
Since we set -e for all tests we run, it's not safe to run a command which can fail.

Signed-off-by: Sorin Dumitru <sdumitru@bloomberg.net>

diff --git a/test/integration/suites/agent-cli/04-check-healthy b/test/integration/suites/agent-cli/04-check-healthy
--- a/test/integration/suites/agent-cli/04-check-healthy
+++ b/test/integration/suites/agent-cli/04-check-healthy
@@ -1,34 +1,22 @@
 #!/bin/bash
 
 RETRIES=20
-AGENT_FOUND=0
-HEALTHCHECK=0
-HEALTHCHECK_FAIL=0
-
 for ((m=1;m<=$RETRIES;m++)); do
     AGENTS=$(docker compose exec -T spire-server /opt/spire/bin/spire-server agent list)
-    if [ "$AGENTS" != "No attested agents found" ]; then
-        AGENT_FOUND=1  
+    if [ "$AGENTS" == "No attested agents found" ]; then
+        continue
     fi
 
-    HEALTH=$(docker compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck)
-    HEALTH_FAIL=$(docker compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck -socketPath invalid/path 2>&1 &)
-
-    if [[ "$HEALTH" =~ "Agent is healthy." ]]; then
-        HEALTHCHECK=1
-    else
-        log-info "Healthcheck failed: ${HEALTH}"
+    if ! docker compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck; then
+        continue
     fi
 
-    if [[ "$HEALTH_FAIL" =~ "Agent is unhealthy: unable to determine health" ]]; then
-        HEALTHCHECK_FAIL=1
-    else
-        log-info "Healthcheck with invalid path did not provide the expected output: ${HEALTH_FAIL}"
+    log-info "Checking for healthcheck failure with invalid path."
+    if docker compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck -socketPath invalid/path 2>&1; then
+        continue
     fi
 
-    if [ $AGENT_FOUND -eq 1 ] && [ $HEALTHCHECK -eq 1 ] && [ $HEALTHCHECK_FAIL -eq 1 ]; then
-        exit 0
-    fi
+    exit 0
 done
 
 fail-now "Agent not found or healthcheck failed."
