Add option to disable JWT-SVID profile on spire server (#6272)
* Add option to disable JWT-SVID profile on spire server

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

* Disabled JWT in intermediateB in nested integration test

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

* New integration test for fetch-jwt-svids

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

* Rename function since it is used by both x509 and jwt

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

* Improve doc description

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

* SetDisableJWTSVIDs only on fakeca

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>

---------

Signed-off-by: Nikolai Tihhomirov <141064611+nikotih@users.noreply.github.com>
Co-authored-by: Sorin Dumitru <sorin@returnze.ro>

diff --git a/test/integration/suites/nested-rotation/10-check-svids b/test/integration/suites/nested-rotation/10-check-svids
--- a/test/integration/suites/nested-rotation/10-check-svids
+++ b/test/integration/suites/nested-rotation/10-check-svids
@@ -32,6 +32,19 @@ validateJWTSVID() {
         -socketPath /opt/spire/sockets/workload_api.sock
 }
 
+log-info "checking intermediateB-agent cannot issue JWT since its disabled"
+if ! ERROR_OUTPUT=$(docker compose exec -u 1001 -T intermediateB-agent \
+      /opt/spire/bin/spire-agent api fetch jwt -audience testIt -socketPath /opt/spire/sockets/workload_api.sock -output json 2>&1); then
+
+    if echo "$ERROR_OUTPUT" | grep -q "code = Unimplemented desc = JWT functionality is disabled"; then
+        log-info "✓ JWT correctly disabled on intermediateB"
+    else
+        fail-now "Expected JWT to be disabled on intermediateB. Got: $ERROR_OUTPUT"
+    fi
+else
+    fail-now "Expected JWT command to fail but it succeeded"
+fi
+
 for ((i=1;i<=NUMCHECKS;i++)); do
     log-info "checking intermediate X509-SVID ($i of $NUMCHECKS)..."
     validateX509SVID "intermediateA-agent" "intermediateB-agent"
