Removing svid_cache_expiry_interval configuration
Signed-off-by: Prasad Borole <prasadb@uber.com>

diff --git a/test/integration/suites/fetch-svids/05-fetch-svids b/test/integration/suites/fetch-svids/05-fetch-svids
--- a/test/integration/suites/fetch-svids/05-fetch-svids
+++ b/test/integration/suites/fetch-svids/05-fetch-svids
@@ -1,14 +1,17 @@
 #!/bin/bash
 
-ENTRYCOUNT=12
+ENTRYCOUNT=10
 CACHESIZE=8
 
-docker-compose exec -u 1001 -T spire-agent \
+X509SVIDCOUNT=`docker-compose exec -u 1001 -T spire-agent \
   /opt/spire/bin/spire-agent api fetch x509 \
-  -socketPath /opt/spire/sockets/workload_api.sock || fail-now "x509-SVID check failed"
+  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed"`
 
-# Call agent debug endpoints and check if svid count is equal number of entries registered
-check-svid-count "spire-agent" $ENTRYCOUNT
+if [ "$X509SVIDCOUNT" -ne "$ENTRYCOUNT" ]; then
+  fail-now "X.509-SVID check failed. Expected $ENTRYCOUNT X.509-SVIDs but received $X509SVIDCOUNT for uid 1001";
+else
+  echo "Expected $ENTRYCOUNT X.509-SVIDs and received $X509SVIDCOUNT for uid 1001";
+fi
 
-# Call agent debug endpoints and check if svids from cache are cleaned up after expiry
-check-svid-count "spire-agent" $CACHESIZE
+# Call agent debug endpoints and check if extra svids from cache are cleaned up
+check-x509-svid-count "spire-agent" $CACHESIZE
diff --git a/test/integration/suites/fetch-svids/07-fetch-svids b/test/integration/suites/fetch-svids/07-fetch-svids
--- a/test/integration/suites/fetch-svids/07-fetch-svids
+++ b/test/integration/suites/fetch-svids/07-fetch-svids
@@ -1,28 +1,27 @@
 #!/bin/bash
 
 CACHESIZE=8
+ENTRYCOUNT=10
 
-docker-compose exec -u 1002 -T spire-agent \
+X509SVIDCOUNT=`docker-compose exec -u 1002 -T spire-agent \
   /opt/spire/bin/spire-agent api fetch x509 \
-  -socketPath /opt/spire/sockets/workload_api.sock || fail-now "x509-SVID check failed"
+  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed"`
 
-# Call agent debug endpoints and check if svid count is equal to cache size limit
-check-svid-count "spire-agent" $CACHESIZE
+if [ "$X509SVIDCOUNT" -ne "$ENTRYCOUNT" ]; then
+  fail-now "X.509-SVID check failed. Expected $ENTRYCOUNT X.509-SVIDs but received $X509SVIDCOUNT for uid 1002";
+else
+  echo "Expected $ENTRYCOUNT X.509-SVIDs and received $X509SVIDCOUNT for uid 1002";
+fi
 
-# introduce some delay between two fetch calls so that we can validate cache cleanup of svids from first fetch.
-sleep 5
-
-docker-compose exec -u 1001 -T spire-agent \
+X509SVIDCOUNT=`docker-compose exec -u 1001 -T spire-agent \
   /opt/spire/bin/spire-agent api fetch x509 \
-  -socketPath /opt/spire/sockets/workload_api.sock || fail-now "x509-SVID check failed"
+  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed"`
 
-# Call agent debug endpoints and check if svid count is equal to 17 (registration entry count for uids 1001 and 1002)
-check-svid-count "spire-agent" 17
+if [ "$X509SVIDCOUNT" -ne "$ENTRYCOUNT" ]; then
+  fail-now "X.509-SVID check failed. Expected $ENTRYCOUNT X.509-SVIDs but received $X509SVIDCOUNT for uid 1001";
+else
+  echo "Expected $ENTRYCOUNT X.509-SVIDs and received $X509SVIDCOUNT for uid 1001";
+fi
 
-# Call agent debug endpoints and check if svid count is equal to 12
-# 17(svid-count) - 5(svids from entries with uuid 1002 will be removed first after svid_cache_expiry_interval) = 12
-check-svid-count "spire-agent" 12
-
-# Call agent debug endpoints and check if svid count is equal to 8
-# 12 - 8(cache size) = 4 extra svids from entries with uuid 1001 will be removed after svid_cache_expiry_interval
-check-svid-count "spire-agent" $CACHESIZE
+# Call agent debug endpoints and check if extra svids from cache are cleaned up
+check-x509-svid-count "spire-agent" $CACHESIZE
