Add agent evict verification
Signed-off-by: Luis Santiago Re <lsantire2@gmail.com>

diff --git a/test/integration/suites/spire-server-cli/06-agent b/test/integration/suites/spire-server-cli/06-agent
--- a/test/integration/suites/spire-server-cli/06-agent
+++ b/test/integration/suites/spire-server-cli/06-agent
@@ -58,3 +58,33 @@ showResult="$(docker-compose exec -T spire-server \
 echo "$showResult" | grep "Found an attested agent given its SPIFFE ID" || fail-now "failed to show agent 3"
 echo "$showResult" | grep "SPIFFE ID" | grep "$agentID3" || fail-now "unexpected SPIFFE ID for agent 3"
 echo "$showResult" | grep "Attestation type" | grep "join_token" || fail-now "unexpected attestation type for agent 3"
+
+# Verify agent evict
+docker-compose exec -T spire-server \
+	/opt/spire/bin/spire-server agent evict -spiffeID "$agentID1" | grep "Agent evicted successfully" || fail-now "failed to evict agent 1"
+
+# Verify agent list after evict
+docker-compose exec -T spire-server \
+    /opt/spire/bin/spire-server agent list | grep "Found 2 attested agents" || fail-now "failed to list the agents after evict"
+
+# Verify agent show after evict
+# Agent 1
+echo "$(docker-compose exec -T spire-server \
+	/opt/spire/bin/spire-server agent show -spiffeID $agentID1 || echo "OK: agent 1 not found")" \
+    | grep "OK: agent 1 not found" || fail-now "agent 1 was found after evict"
+
+# Agent 2
+showResult="$(docker-compose exec -T spire-server \
+	/opt/spire/bin/spire-server agent show -spiffeID $agentID2)"
+
+echo "$showResult" | grep "Found an attested agent given its SPIFFE ID" || fail-now "failed to show agent 2"
+echo "$showResult" | grep "SPIFFE ID" | grep "$agentID2" || fail-now "unexpected SPIFFE ID for agent 2"
+echo "$showResult" | grep "Attestation type" | grep "join_token" || fail-now "unexpected attestation type for agent 2"
+
+# Agent 3
+showResult="$(docker-compose exec -T spire-server \
+	/opt/spire/bin/spire-server agent show -spiffeID $agentID3)"
+
+echo "$showResult" | grep "Found an attested agent given its SPIFFE ID" || fail-now "failed to show agent 3"
+echo "$showResult" | grep "SPIFFE ID" | grep "$agentID3" || fail-now "unexpected SPIFFE ID for agent 3"
+echo "$showResult" | grep "Attestation type" | grep "join_token" || fail-now "unexpected attestation type for agent 3"
