Updating method signature of SubscribeToCacheChanges to take ctx
Signed-off-by: Prasad Borole <prasadb@uber.com>

diff --git a/test/integration/suites/fetch-x509-svids/07-fetch-x509-svids b/test/integration/suites/fetch-x509-svids/07-fetch-x509-svids
--- a/test/integration/suites/fetch-x509-svids/07-fetch-x509-svids
+++ b/test/integration/suites/fetch-x509-svids/07-fetch-x509-svids
@@ -3,9 +3,9 @@
 CACHESIZE=8
 ENTRYCOUNT=10
 
-X509SVIDCOUNT=`docker-compose exec -u 1002 -T spire-agent \
+X509SVIDCOUNT=$(docker-compose exec -u 1002 -T spire-agent \
   /opt/spire/bin/spire-agent api fetch x509 \
-  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed"`
+  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed")
 
 if [ "$X509SVIDCOUNT" -ne "$ENTRYCOUNT" ]; then
   fail-now "X.509-SVID check failed. Expected $ENTRYCOUNT X.509-SVIDs but received $X509SVIDCOUNT for uid 1002";
@@ -13,9 +13,9 @@ else
   echo "Expected $ENTRYCOUNT X.509-SVIDs and received $X509SVIDCOUNT for uid 1002";
 fi
 
-X509SVIDCOUNT=`docker-compose exec -u 1001 -T spire-agent \
+X509SVIDCOUNT=$(docker-compose exec -u 1001 -T spire-agent \
   /opt/spire/bin/spire-agent api fetch x509 \
-  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed"`
+  -socketPath /opt/spire/sockets/workload_api.sock | grep -i "spiffe://domain.test" | wc -l || fail-now "X.509-SVID check failed")
 
 if [ "$X509SVIDCOUNT" -ne "$ENTRYCOUNT" ]; then
   fail-now "X.509-SVID check failed. Expected $ENTRYCOUNT X.509-SVIDs but received $X509SVIDCOUNT for uid 1001";
